# It contains all the configs required in the project
params:
  validation_datasize: 5000
  seed: 2021
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: adam
  num_classes: 10
  epochs: 10
  num_classes_transfer_model: 2
  epochs_transfer_model: 10

artifacts:
  artifacts_dir: artifacts
  model_dir: model
  base_model_name: base_model.h5
  transfer_model_name: transfer_model.h5
