# It contains all the configs required in the project
params:
  validation_datasize: 5000
  seed: 2021
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  num_classes: 10
  epochs: 10

artifacts:
  artifacts_dir: artifacts
  model_dir: model
  base_model_name: base_model.h5
